[2022-02-27 22:05:05,626] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: historical_fuel_data_ingestion.create_fuel_dataset scheduled__2022-02-18T10:00:00+00:00 [queued]>
[2022-02-27 22:05:05,693] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: historical_fuel_data_ingestion.create_fuel_dataset scheduled__2022-02-18T10:00:00+00:00 [queued]>
[2022-02-27 22:05:05,694] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2022-02-27 22:05:05,694] {taskinstance.py:1244} INFO - Starting attempt 1 of 2
[2022-02-27 22:05:05,694] {taskinstance.py:1245} INFO - 
--------------------------------------------------------------------------------
[2022-02-27 22:05:05,784] {taskinstance.py:1264} INFO - Executing <Task(PythonOperator): create_fuel_dataset> on 2022-02-18 10:00:00+00:00
[2022-02-27 22:05:05,796] {standard_task_runner.py:52} INFO - Started process 85 to run task
[2022-02-27 22:05:05,816] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'historical_fuel_data_ingestion', 'create_fuel_dataset', 'scheduled__2022-02-18T10:00:00+00:00', '--job-id', '68', '--raw', '--subdir', 'DAGS_FOLDER/ingest_historical_fuel_data_dag.py', '--cfg-path', '/tmp/tmpuklvctwn', '--error-file', '/tmp/tmp8o5b05d5']
[2022-02-27 22:05:05,820] {standard_task_runner.py:77} INFO - Job 68: Subtask create_fuel_dataset
[2022-02-27 22:05:06,062] {logging_mixin.py:109} INFO - Running <TaskInstance: historical_fuel_data_ingestion.create_fuel_dataset scheduled__2022-02-18T10:00:00+00:00 [running]> on host daf54b46ba6b
[2022-02-27 22:05:06,153] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:156: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2022-02-27 22:05:06,229] {taskinstance.py:1431} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=historical_fuel_data_ingestion
AIRFLOW_CTX_TASK_ID=create_fuel_dataset
AIRFLOW_CTX_EXECUTION_DATE=2022-02-18T10:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-02-18T10:00:00+00:00
[2022-02-27 22:05:06,236] {taskinstance.py:1718} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1334, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1460, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1516, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 188, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/ingest_historical_fuel_data_dag.py", line 29, in get_historical_fuel_data
    src_file, sheet_name="Diesel TGP"
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/excel/_base.py", line 364, in read_excel
    io = ExcelFile(io, storage_options=storage_options, engine=engine)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/excel/_base.py", line 1233, in __init__
    self._reader = self._engines[engine](self._io, storage_options=storage_options)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/excel/_openpyxl.py", line 521, in __init__
    import_optional_dependency("openpyxl")
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/compat/_optional.py", line 118, in import_optional_dependency
    raise ImportError(msg) from None
ImportError: Missing optional dependency 'openpyxl'.  Use pip or conda to install openpyxl.
[2022-02-27 22:05:06,288] {taskinstance.py:1282} INFO - Marking task as UP_FOR_RETRY. dag_id=historical_fuel_data_ingestion, task_id=create_fuel_dataset, execution_date=20220218T100000, start_date=20220227T220505, end_date=20220227T220506
[2022-02-27 22:05:06,322] {standard_task_runner.py:92} ERROR - Failed to execute job 68 for task create_fuel_dataset
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 184, in _run_raw_task
    error_file=args.error_file,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1334, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1460, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1516, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 188, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/ingest_historical_fuel_data_dag.py", line 29, in get_historical_fuel_data
    src_file, sheet_name="Diesel TGP"
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/excel/_base.py", line 364, in read_excel
    io = ExcelFile(io, storage_options=storage_options, engine=engine)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/excel/_base.py", line 1233, in __init__
    self._reader = self._engines[engine](self._io, storage_options=storage_options)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/excel/_openpyxl.py", line 521, in __init__
    import_optional_dependency("openpyxl")
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/compat/_optional.py", line 118, in import_optional_dependency
    raise ImportError(msg) from None
ImportError: Missing optional dependency 'openpyxl'.  Use pip or conda to install openpyxl.
[2022-02-27 22:05:06,354] {local_task_job.py:154} INFO - Task exited with return code 1
[2022-02-27 22:05:06,446] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-02-28 22:17:57,148] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: historical_fuel_data_ingestion.create_fuel_dataset scheduled__2022-02-18T10:00:00+00:00 [queued]>
[2022-02-28 22:17:57,169] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: historical_fuel_data_ingestion.create_fuel_dataset scheduled__2022-02-18T10:00:00+00:00 [queued]>
[2022-02-28 22:17:57,169] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2022-02-28 22:17:57,169] {taskinstance.py:1244} INFO - Starting attempt 1 of 2
[2022-02-28 22:17:57,169] {taskinstance.py:1245} INFO - 
--------------------------------------------------------------------------------
[2022-02-28 22:17:57,186] {taskinstance.py:1264} INFO - Executing <Task(PythonOperator): create_fuel_dataset> on 2022-02-18 10:00:00+00:00
[2022-02-28 22:17:57,195] {standard_task_runner.py:52} INFO - Started process 875 to run task
[2022-02-28 22:17:57,206] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'historical_fuel_data_ingestion', 'create_fuel_dataset', 'scheduled__2022-02-18T10:00:00+00:00', '--job-id', '100', '--raw', '--subdir', 'DAGS_FOLDER/ingest_historical_fuel_data_dag.py', '--cfg-path', '/tmp/tmpgx5kq11i', '--error-file', '/tmp/tmpi89e2v6p']
[2022-02-28 22:17:57,208] {standard_task_runner.py:77} INFO - Job 100: Subtask create_fuel_dataset
[2022-02-28 22:17:57,373] {logging_mixin.py:109} INFO - Running <TaskInstance: historical_fuel_data_ingestion.create_fuel_dataset scheduled__2022-02-18T10:00:00+00:00 [running]> on host ee95ca064caf
[2022-02-28 22:17:57,468] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:156: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2022-02-28 22:17:57,509] {taskinstance.py:1431} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=historical_fuel_data_ingestion
AIRFLOW_CTX_TASK_ID=create_fuel_dataset
AIRFLOW_CTX_EXECUTION_DATE=2022-02-18T10:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-02-18T10:00:00+00:00
[2022-02-28 22:17:59,393] {python.py:175} INFO - Done. Returned value was: None
[2022-02-28 22:17:59,409] {taskinstance.py:1282} INFO - Marking task as SUCCESS. dag_id=historical_fuel_data_ingestion, task_id=create_fuel_dataset, execution_date=20220218T100000, start_date=20220228T221757, end_date=20220228T221759
[2022-02-28 22:17:59,455] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-02-28 22:17:59,501] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
